name: 'Premium plan: question ❔'
description: I'm a Premium plan user, I can't find a solution to my problem with MUI X.
title: '[question] '
labels: ['status: needs triage', 'Premium plan', 'support: commercial']
body:
  - type: markdown
    attributes:
      value: |
        Please provide a searchable summary of the issue in the title above ⬆️.

        ⚠️ **Don't use this form if the problem is [a bug](https://github.com/mui/mui-x/issues/new?assignees=&labels=status%3A+needs+triage&template=1.bug.yml) or a [feature request](https://github.com/mui/mui-x/issues/new?assignees=&labels=status%3A+needs+triage&template=2.feature.yml), use the dedicated form instead.**

  - type: input
    id: contact
    attributes:
      label: Order ID or Support key 💳
      description: The order ID of the purchased Premium plan. Community users can [learn more about support](https://mui.com/getting-started/support/) in the documentation.
      placeholder: 'e.g. 11111'
    validations:
      required: true

  - type: input
    attributes:
      label: Search keywords
      description: Your issue may have already been reported! List the keywords you've used to search the [existing issues](https://github.com/mui/mui-x/issues). This will also make your issue searchable for others.
      placeholder: e.g. datagrid column resizing
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Latest version
      description: We roll bug fixes, performance enhancements, and other improvements into new releases.
      options:
        - label: I have tested the latest version
          required: true

  - type: textarea
    attributes:
      label: The problem in depth 🔍
      description: |
        **If you're reporting a bug, please provide a live example for your report.**
        If you don't have one, you can use one of these options:
          - [DataGrid codesandbox template](https://codesandbox.io/s/github/mui/mui-x/tree/master/templates/x-data-grid?file=/demo.tsx)
          - Fork any of the examples in our [documentation](https://mui.com/x/introduction/) by [clicking on the codesandbox or stackblitz icon](https://mui.com/static/docs/forking-an-example.png)
  - type: textarea
    attributes:
      label: Your environment 🌎
      description: Run `npx @mui/envinfo` and post the results. If you encounter issues with TypeScript please include the used tsconfig.
      value: |
        <details>
          <summary>`npx @mui/envinfo`</summary>

        ```
          Don't forget to mention which browser you used.
          Output from `npx @mui/envinfo` goes here.
        ```
        </details>
