name: 'Priority support: SLA ⏰'
description: I'm an MUI X Premium user and we have purchased the Priority Support add-on. I can't find a solution to my problem with MUI X.
title: '[question] '
labels: ['status: needs triage', 'support: commercial', 'support: unknown']
body:
  - type: markdown
    attributes:
      value: |
        Please provide a searchable summary of the issue in the title above ⬆️.

  - type: input
    attributes:
      label: Search keywords
      description: Your issue may have already been reported! List the keywords you've used to search the [existing issues](https://github.com/mui/mui-x/issues). This will allow make your issue searchable for others.
      placeholder: e.g. datagrid column resizing
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Latest version
      description: We roll bug fixes, performance enhancements, and other improvements into new releases.
      options:
        - label: I have tested the latest version
          required: true

  - type: textarea
    attributes:
      label: The problem in depth 🔍
      description: |
        **If you're reporting a bug, please provide a live example for your report.**
        If you don't have one, you can use one of these options:
          - [DataGrid codesandbox template](https://codesandbox.io/s/github/mui/mui-x/tree/master/templates/x-data-grid?file=demo.tsx)
          - Fork any of the examples in our [documentation](https://mui.com/x/introduction/) by [clicking on the codesandbox or stackblitz icon](https://mui.com/static/docs/forking-an-example.png)
  - type: textarea
    attributes:
      label: Your environment 🌎
      description: Run `npx @mui/envinfo` and post the results. If you encounter issues with TypeScript please include the used tsconfig.
      value: |
        <details>
          <summary>`npx @mui/envinfo`</summary>

        ```
          Don't forget to mention which browser you used.
          Output from `npx @mui/envinfo` goes here.
        ```
        </details>
